# Generated by Django 2.0 on 2017-12-07 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlikes',
            unique_together={('post', 'user')},
        ),
    ]
