# Generated by Django 2.0 on 2017-12-04 17:19

import FB_Replica.shared_utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media/Images/User/default_user.png', upload_to=FB_Replica.shared_utils.UploadToPathAndRename('media/Images/User/'))),
                ('street', models.TextField(blank=True, max_length=254)),
                ('city', models.TextField(blank=True, max_length=254)),
                ('state', models.TextField(blank=True, max_length=254)),
                ('country', models.TextField(blank=True, max_length=254)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'O')], max_length=37, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
