# Generated by Django 2.0 on 2017-12-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'M'), ('Female', 'F'), ('Others', 'O')], default='Male', max_length=37, null=True),
        ),
    ]
